owner: axislinux
repo: status

sites:
  - name: Axis Linux
    url: https://axislinux.org
  - name: Axis Linux Docs
    url: https://docs.axislinux.org
  - name: Axis Linux Status
    url: https://status.axislinux.org
  - name: Axis Linux Repo
    url: https://repo.axislinux.org
